# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  ccusage = {
    pname = "ccusage";
    version = "17.1.3";
    src = fetchurl {
      url = "https://registry.npmjs.org/ccusage/-/ccusage-17.1.3.tgz";
      sha256 = "sha256-yK5Js1QEJ/QY0AufJFUz6CyEX5cO2hmsscIXyTCCJFw=";
    };
  };
  claude-code = {
    pname = "claude-code";
    version = "2.0.26";
    src = fetchurl {
      url = "https://registry.npmjs.org/@anthropic-ai/claude-code/-/claude-code-2.0.26.tgz";
      sha256 = "sha256-Bh087VnFRrp5agxcq+4gzSGS1rhYZKnXra1kSfJGyWs=";
    };
  };
  disable-checkout-persist-credentials = {
    pname = "disable-checkout-persist-credentials";
    version = "v0.1.3";
    src = fetchFromGitHub {
      owner = "suzuki-shunsuke";
      repo = "disable-checkout-persist-credentials";
      rev = "v0.1.3";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sparseCheckout = [ ];
      sha256 = "sha256-fJK9jtoy7z9tluloU0S0/QAUVQ/m4plInCA1jqlAVwc=";
    };
  };
  duckgo = {
    pname = "duckgo";
    version = "v0.1.1";
    src = fetchFromGitHub {
      owner = "sheepla";
      repo = "duckgo";
      rev = "v0.1.1";
      fetchSubmodules = false;
      sha256 = "sha256-+wJexVAKTqEOTyV+PcNcUe5r9Q4MpGx9EnuxiQHq0G0=";
    };
  };
  firge = {
    pname = "firge";
    version = "v0.3.0";
    src = fetchurl {
      url = "https://github.com/yuru7/Firge/releases/download/v0.3.0/Firge_v0.3.0.zip";
      sha256 = "sha256-yYb2IQAKZZgGTH4geDIu0CBAr094BNJYAz35SbNbBSc=";
    };
  };
  firge-nerd = {
    pname = "firge-nerd";
    version = "v0.3.0";
    src = fetchurl {
      url = "https://github.com/yuru7/Firge/releases/download/v0.3.0/FirgeNerd_v0.3.0.zip";
      sha256 = "sha256-VM12N4+8UCX0LUQdlcpuwdPsxCcOYQdViED+18BM/k8=";
    };
  };
  gh-dep = {
    pname = "gh-dep";
    version = "v0.7.0";
    src = fetchFromGitHub {
      owner = "jackchuka";
      repo = "gh-dep";
      rev = "v0.7.0";
      fetchSubmodules = false;
      sha256 = "sha256-KMGAzvEVdGH3lK294VtU8HnGJsczHyHxNG44NKo0Jg8=";
    };
  };
  gh-grep = {
    pname = "gh-grep";
    version = "v1.2.5";
    src = fetchFromGitHub {
      owner = "k1LoW";
      repo = "gh-grep";
      rev = "v1.2.5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sparseCheckout = [ ];
      sha256 = "sha256-hOnWydVs58Dv3FtFuKkbXylwvdhuvz92KJBhSZSVyhA=";
    };
  };
  gh-triage = {
    pname = "gh-triage";
    version = "v0.10.2";
    src = fetchFromGitHub {
      owner = "k1LoW";
      repo = "gh-triage";
      rev = "v0.10.2";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sparseCheckout = [ ];
      sha256 = "sha256-9JeV8R/gophbgrE9L3sT87Q0ciYQgGFE7+wMjCSWR7I=";
    };
  };
  ghalint = {
    pname = "ghalint";
    version = "v1.5.3";
    src = fetchFromGitHub {
      owner = "suzuki-shunsuke";
      repo = "ghalint";
      rev = "v1.5.3";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sparseCheckout = [ ];
      sha256 = "sha256-iX2Rk1tJ7yKm7uXENmvzwkeSnTebQTD6gxc4yhoQEj8=";
    };
  };
  ghatm = {
    pname = "ghatm";
    version = "v0.3.7";
    src = fetchFromGitHub {
      owner = "suzuki-shunsuke";
      repo = "ghatm";
      rev = "v0.3.7";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sparseCheckout = [ ];
      sha256 = "sha256-AgKqQl3wgfsR5RMtEzkZfKoT5DDBvNLWlJrsbBTOo5E=";
    };
  };
  ghq = {
    pname = "ghq";
    version = "v1.8.0";
    src = fetchFromGitHub {
      owner = "x-motemen";
      repo = "ghq";
      rev = "v1.8.0";
      fetchSubmodules = false;
      sha256 = "sha256-5BN96/RShfJpkfpJe0qrZVDuyFoAV9kgCiBv4REY/5Y=";
    };
  };
  gitlab-ci-ls = {
    pname = "gitlab-ci-ls";
    version = "1.2.2";
    src = fetchFromGitHub {
      owner = "alesbrelih";
      repo = "gitlab-ci-ls";
      rev = "1.2.2";
      fetchSubmodules = false;
      sha256 = "sha256-ZpLkiTJP3pofDcXrQPdl5Vm6SKsp6DecwSfXWC9h2qI=";
    };
  };
  gitlab-ci-verify = {
    pname = "gitlab-ci-verify";
    version = "v2.4.3";
    src = fetchFromGitHub {
      owner = "timo-reymann";
      repo = "gitlab-ci-verify";
      rev = "v2.4.3";
      fetchSubmodules = false;
      sha256 = "sha256-gyjqpWAsHl2UHr6/ZmZRB1DSFSSELdbXz5YNRcevxeE=";
    };
  };
  ibm-plex-sans-jp = {
    pname = "ibm-plex-sans-jp";
    version = "@ibm/plex-sans-jp@3.0.0";
    src = fetchurl {
      url = "https://github.com/IBM/plex/releases/download/@ibm/plex-sans-jp@3.0.0/ibm-plex-sans-jp.zip";
      sha256 = "sha256-TBTEFVKTSwvJL8IWp2s2vcePdF377tERX5uLxAXuMU8=";
    };
  };
  lazygit = {
    pname = "lazygit";
    version = "v0.55.1";
    src = fetchFromGitHub {
      owner = "jesseduffield";
      repo = "lazygit";
      rev = "v0.55.1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sparseCheckout = [ ];
      sha256 = "sha256-gvqubpUmDXbnG0C509Tz2CvzjJaEXAyxfVO6ztN0by4=";
    };
  };
  octocov = {
    pname = "octocov";
    version = "v0.73.0";
    src = fetchFromGitHub {
      owner = "k1LoW";
      repo = "octocov";
      rev = "v0.73.0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sparseCheckout = [ ];
      sha256 = "sha256-GcanXDKrOIUoCHhgzfzIYjUFr32yLulQZgtSQ8GIZmQ=";
    };
  };
  pinact = {
    pname = "pinact";
    version = "v3.4.2";
    src = fetchFromGitHub {
      owner = "suzuki-shunsuke";
      repo = "pinact";
      rev = "v3.4.2";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sparseCheckout = [ ];
      sha256 = "sha256-G32GI5c/+SMuLvLSiiC09vxcYol7W2GbRfvqria3ATg=";
    };
  };
  roots = {
    pname = "roots";
    version = "v0.4.0";
    src = fetchFromGitHub {
      owner = "k1LoW";
      repo = "roots";
      rev = "v0.4.0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sparseCheckout = [ ];
      sha256 = "sha256-8vvpUCAIm9Pg61VwiUaP1Xs7HkBE7mUt0Ge6rVQ5oPs=";
    };
  };
  slack-reminder = {
    pname = "slack-reminder";
    version = "v0.1.1";
    src = fetchFromGitHub {
      owner = "skanehira";
      repo = "slack-reminder";
      rev = "v0.1.1";
      fetchSubmodules = false;
      sha256 = "sha256-1MzRZ8E1wtwThnaXteMkAapX5kLFbEi3ix1csatSFF8=";
    };
  };
  sort-package-json = {
    pname = "sort-package-json";
    version = "v3.4.0";
    src = fetchFromGitHub {
      owner = "keithamus";
      repo = "sort-package-json";
      rev = "v3.4.0";
      fetchSubmodules = false;
      sha256 = "sha256-CnMWuokQistBfvyyPHJTqAlVj+8r4CcZ8VGYRKB1Mmo=";
    };
  };
  vim-startuptime = {
    pname = "vim-startuptime";
    version = "v1.3.2";
    src = fetchFromGitHub {
      owner = "rhysd";
      repo = "vim-startuptime";
      rev = "v1.3.2";
      fetchSubmodules = false;
      sha256 = "sha256-d6AXTWTUawkBCXCvMs3C937qoRUZmy0qCFdSLcWh0BE=";
    };
  };
}
