# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  cc-sdd = {
    pname = "cc-sdd";
    version = "2.0.3";
    src = fetchurl {
      url = "https://registry.npmjs.org/cc-sdd/-/cc-sdd-2.0.3.tgz";
      sha256 = "sha256-QGSct0riYB8ndhsgg5h1/qZb86R3wGpUzlpf4MYfvcM=";
    };
  };
  ccusage = {
    pname = "ccusage";
    version = "17.2.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/ccusage/-/ccusage-17.2.0.tgz";
      sha256 = "sha256-jCi9Q7depEBUGRBnnfq05L9znDs72igAE2+crnOv2nY=";
    };
  };
  claude-code = {
    pname = "claude-code";
    version = "2.0.74";
    src = fetchurl {
      url = "https://registry.npmjs.org/@anthropic-ai/claude-code/-/claude-code-2.0.74.tgz";
      sha256 = "sha256-gb1iKyhXtnKClcuhg2hrVOxYgQisy2pRnILIbfKVjCk=";
    };
  };
  disable-checkout-persist-credentials = {
    pname = "disable-checkout-persist-credentials";
    version = "v1.0.0";
    src = fetchFromGitHub {
      owner = "suzuki-shunsuke";
      repo = "disable-checkout-persist-credentials";
      rev = "v1.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-TEjUf7Uc049g/ZRuKMtWYxod+ZN5dKabDINJgqXxkuk=";
    };
  };
  duckgo = {
    pname = "duckgo";
    version = "v0.1.1";
    src = fetchFromGitHub {
      owner = "sheepla";
      repo = "duckgo";
      rev = "v0.1.1";
      fetchSubmodules = false;
      sha256 = "sha256-+wJexVAKTqEOTyV+PcNcUe5r9Q4MpGx9EnuxiQHq0G0=";
    };
  };
  firge = {
    pname = "firge";
    version = "v0.3.0";
    src = fetchurl {
      url = "https://github.com/yuru7/Firge/releases/download/v0.3.0/Firge_v0.3.0.zip";
      sha256 = "sha256-yYb2IQAKZZgGTH4geDIu0CBAr094BNJYAz35SbNbBSc=";
    };
  };
  firge-nerd = {
    pname = "firge-nerd";
    version = "v0.3.0";
    src = fetchurl {
      url = "https://github.com/yuru7/Firge/releases/download/v0.3.0/FirgeNerd_v0.3.0.zip";
      sha256 = "sha256-VM12N4+8UCX0LUQdlcpuwdPsxCcOYQdViED+18BM/k8=";
    };
  };
  gh-dep = {
    pname = "gh-dep";
    version = "v0.9.0";
    src = fetchFromGitHub {
      owner = "jackchuka";
      repo = "gh-dep";
      rev = "v0.9.0";
      fetchSubmodules = false;
      sha256 = "sha256-+HCG4ZE53jkOGmcGTXu8ADsI5sfnVllLjFqf7Q1lEQg=";
    };
  };
  gh-grep = {
    pname = "gh-grep";
    version = "v1.2.5";
    src = fetchFromGitHub {
      owner = "k1LoW";
      repo = "gh-grep";
      rev = "v1.2.5";
      fetchSubmodules = false;
      sha256 = "sha256-xCr68IMrGPIQr+RmAgNdgD+Bw0dQSSi9GcpoDy3q86U=";
    };
  };
  gh-triage = {
    pname = "gh-triage";
    version = "v0.11.0";
    src = fetchFromGitHub {
      owner = "k1LoW";
      repo = "gh-triage";
      rev = "v0.11.0";
      fetchSubmodules = false;
      sha256 = "sha256-aa98DfXxyOuk1Q7yYGKNqYqTa9tuNP57hYwNqIYxPeo=";
    };
  };
  ghalint = {
    pname = "ghalint";
    version = "v1.5.3";
    src = fetchFromGitHub {
      owner = "suzuki-shunsuke";
      repo = "ghalint";
      rev = "v1.5.3";
      fetchSubmodules = false;
      sha256 = "sha256-zll71vSqSKIij/TUi4LnGtVqmLhK9UViFDkpnuEvmz8=";
    };
  };
  ghatm = {
    pname = "ghatm";
    version = "v0.3.7";
    src = fetchFromGitHub {
      owner = "suzuki-shunsuke";
      repo = "ghatm";
      rev = "v0.3.7";
      fetchSubmodules = false;
      sha256 = "sha256-t8DjUHsbU1ovBaB2bINEG7gpm1MFQCnoanunfrrTKWU=";
    };
  };
  ghq = {
    pname = "ghq";
    version = "v1.8.0";
    src = fetchFromGitHub {
      owner = "x-motemen";
      repo = "ghq";
      rev = "v1.8.0";
      fetchSubmodules = false;
      sha256 = "sha256-5BN96/RShfJpkfpJe0qrZVDuyFoAV9kgCiBv4REY/5Y=";
    };
  };
  gitlab-ci-ls = {
    pname = "gitlab-ci-ls";
    version = "1.2.4";
    src = fetchFromGitHub {
      owner = "alesbrelih";
      repo = "gitlab-ci-ls";
      rev = "1.2.4";
      fetchSubmodules = false;
      sha256 = "sha256-J7VdaD9RfaEv7J0RE4ffZnp0RkMtFmHWEHVnmaXMUdI=";
    };
  };
  gitlab-ci-verify = {
    pname = "gitlab-ci-verify";
    version = "v2.7.3";
    src = fetchFromGitHub {
      owner = "timo-reymann";
      repo = "gitlab-ci-verify";
      rev = "v2.7.3";
      fetchSubmodules = false;
      sha256 = "sha256-t5QJMSBxBN0McAnQtaaND+mAQyVQ2hfk179c0Yp4ED0=";
    };
  };
  ibm-plex-sans-jp = {
    pname = "ibm-plex-sans-jp";
    version = "@ibm/plex-sans-jp@3.0.0";
    src = fetchurl {
      url = "https://github.com/IBM/plex/releases/download/@ibm/plex-sans-jp@3.0.0/ibm-plex-sans-jp.zip";
      sha256 = "sha256-TBTEFVKTSwvJL8IWp2s2vcePdF377tERX5uLxAXuMU8=";
    };
  };
  lazygit = {
    pname = "lazygit";
    version = "v0.57.0";
    src = fetchFromGitHub {
      owner = "jesseduffield";
      repo = "lazygit";
      rev = "v0.57.0";
      fetchSubmodules = false;
      sha256 = "sha256-DC0wVkFI7Te3QSE8Y0WU/ysanfukTkGa3N43hmKHXW8=";
    };
  };
  octocov = {
    pname = "octocov";
    version = "v0.74.1";
    src = fetchFromGitHub {
      owner = "k1LoW";
      repo = "octocov";
      rev = "v0.74.1";
      fetchSubmodules = false;
      sha256 = "sha256-JypTAcBrAo2Z95c3MfWhRUODV9RPJqCF/5zZw7jGruU=";
    };
  };
  pinact = {
    pname = "pinact";
    version = "v3.4.5";
    src = fetchFromGitHub {
      owner = "suzuki-shunsuke";
      repo = "pinact";
      rev = "v3.4.5";
      fetchSubmodules = false;
      sha256 = "sha256-YupEKk8s8NMKcj3TjKYt1/bPpHEA1UGSjbeX4wd+f7U=";
    };
  };
  roots = {
    pname = "roots";
    version = "v0.4.0";
    src = fetchFromGitHub {
      owner = "k1LoW";
      repo = "roots";
      rev = "v0.4.0";
      fetchSubmodules = false;
      sha256 = "sha256-NOUxbYp3dPJiK6ZJ96tyCrdQfeQWMsWfwIpinIQfowU=";
    };
  };
  slack-reminder = {
    pname = "slack-reminder";
    version = "v0.1.1";
    src = fetchFromGitHub {
      owner = "skanehira";
      repo = "slack-reminder";
      rev = "v0.1.1";
      fetchSubmodules = false;
      sha256 = "sha256-1MzRZ8E1wtwThnaXteMkAapX5kLFbEi3ix1csatSFF8=";
    };
  };
  sort-package-json = {
    pname = "sort-package-json";
    version = "v3.4.0";
    src = fetchFromGitHub {
      owner = "keithamus";
      repo = "sort-package-json";
      rev = "v3.4.0";
      fetchSubmodules = false;
      sha256 = "sha256-CnMWuokQistBfvyyPHJTqAlVj+8r4CcZ8VGYRKB1Mmo=";
    };
  };
  vim-startuptime = {
    pname = "vim-startuptime";
    version = "v1.3.2";
    src = fetchFromGitHub {
      owner = "rhysd";
      repo = "vim-startuptime";
      rev = "v1.3.2";
      fetchSubmodules = false;
      sha256 = "sha256-d6AXTWTUawkBCXCvMs3C937qoRUZmy0qCFdSLcWh0BE=";
    };
  };
}
