# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  ccusage = {
    pname = "ccusage";
    version = "15.2.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/ccusage/-/ccusage-15.2.0.tgz";
      sha256 = "sha256-rMRHWSeGN+xiKp89VF0NiKUWbBxFFWEO3nhSeQlq4DM=";
    };
  };
  claude-code = {
    pname = "claude-code";
    version = "1.0.43";
    src = fetchurl {
      url = "https://registry.npmjs.org/@anthropic-ai/claude-code/-/claude-code-1.0.43.tgz";
      sha256 = "sha256-t8XunDJEt8jdShec4AtelTBmQ3KtWPMOgMxjxuMveRU=";
    };
  };
  disable-checkout-persist-credentials = {
    pname = "disable-checkout-persist-credentials";
    version = "v0.1.2";
    src = fetchFromGitHub {
      owner = "suzuki-shunsuke";
      repo = "disable-checkout-persist-credentials";
      rev = "v0.1.2";
      fetchSubmodules = false;
      sha256 = "sha256-X1qsOhp7L8jNxuJE/MxowkhUZ0YvVjoljvVlG0JaTQg=";
    };
  };
  duckgo = {
    pname = "duckgo";
    version = "v0.1.1";
    src = fetchFromGitHub {
      owner = "sheepla";
      repo = "duckgo";
      rev = "v0.1.1";
      fetchSubmodules = false;
      sha256 = "sha256-+wJexVAKTqEOTyV+PcNcUe5r9Q4MpGx9EnuxiQHq0G0=";
    };
  };
  firge = {
    pname = "firge";
    version = "v0.3.0";
    src = fetchurl {
      url = "https://github.com/yuru7/Firge/releases/download/v0.3.0/Firge_v0.3.0.zip";
      sha256 = "sha256-yYb2IQAKZZgGTH4geDIu0CBAr094BNJYAz35SbNbBSc=";
    };
  };
  firge-nerd = {
    pname = "firge-nerd";
    version = "v0.3.0";
    src = fetchurl {
      url = "https://github.com/yuru7/Firge/releases/download/v0.3.0/FirgeNerd_v0.3.0.zip";
      sha256 = "sha256-VM12N4+8UCX0LUQdlcpuwdPsxCcOYQdViED+18BM/k8=";
    };
  };
  ghalint = {
    pname = "ghalint";
    version = "v1.5.1";
    src = fetchFromGitHub {
      owner = "suzuki-shunsuke";
      repo = "ghalint";
      rev = "v1.5.1";
      fetchSubmodules = false;
      sha256 = "sha256-uZYd94dzdYMpbFXBMUa4nFYbVcO3f93/9QXKtPjycbg=";
    };
  };
  ghatm = {
    pname = "ghatm";
    version = "v0.3.5";
    src = fetchFromGitHub {
      owner = "suzuki-shunsuke";
      repo = "ghatm";
      rev = "v0.3.5";
      fetchSubmodules = false;
      sha256 = "sha256-CPyZkvO1+WSQvHN4YWNEs9sTk9XiYq5kRGk+JsTM8xE=";
    };
  };
  ghq = {
    pname = "ghq";
    version = "v1.8.0";
    src = fetchFromGitHub {
      owner = "x-motemen";
      repo = "ghq";
      rev = "v1.8.0";
      fetchSubmodules = false;
      sha256 = "sha256-5BN96/RShfJpkfpJe0qrZVDuyFoAV9kgCiBv4REY/5Y=";
    };
  };
  gitlab-ci-ls = {
    pname = "gitlab-ci-ls";
    version = "1.1.1";
    src = fetchFromGitHub {
      owner = "alesbrelih";
      repo = "gitlab-ci-ls";
      rev = "1.1.1";
      fetchSubmodules = false;
      sha256 = "sha256-3DR1MV9YSugWFodLh4wBa6oT8yGEkir0rVm0mcHXpxU=";
    };
  };
  gitlab-ci-verify = {
    pname = "gitlab-ci-verify";
    version = "v2.1.12";
    src = fetchFromGitHub {
      owner = "timo-reymann";
      repo = "gitlab-ci-verify";
      rev = "v2.1.12";
      fetchSubmodules = false;
      sha256 = "sha256-dZZHRIbfoA58NlWpvlEgb3CpeKb2TS6/Y85otj32rcE=";
    };
  };
  lazygit = {
    pname = "lazygit";
    version = "v0.52.0";
    src = fetchFromGitHub {
      owner = "jesseduffield";
      repo = "lazygit";
      rev = "v0.52.0";
      fetchSubmodules = false;
      sha256 = "sha256-tbFRovaB0f+0VyX34DEXvWYjV3fipc5kbRNhm7rVMlo=";
    };
  };
  octocov = {
    pname = "octocov";
    version = "v0.68.1";
    src = fetchFromGitHub {
      owner = "k1LoW";
      repo = "octocov";
      rev = "v0.68.1";
      fetchSubmodules = false;
      sha256 = "sha256-rs/rKvybyIlUa48NgaOfFMXyzIuUCG7lQaZqP5i5KDM=";
    };
  };
  pinact = {
    pname = "pinact";
    version = "v3.3.0";
    src = fetchFromGitHub {
      owner = "suzuki-shunsuke";
      repo = "pinact";
      rev = "v3.3.0";
      fetchSubmodules = false;
      sha256 = "sha256-aNRDz0mAc5fsS01W0PZxCGw0NgEcExtciTcv/Omdv3g=";
    };
  };
  roots = {
    pname = "roots";
    version = "v0.4.0";
    src = fetchFromGitHub {
      owner = "k1LoW";
      repo = "roots";
      rev = "v0.4.0";
      fetchSubmodules = false;
      sha256 = "sha256-NOUxbYp3dPJiK6ZJ96tyCrdQfeQWMsWfwIpinIQfowU=";
    };
  };
  slack-reminder = {
    pname = "slack-reminder";
    version = "v0.1.1";
    src = fetchFromGitHub {
      owner = "skanehira";
      repo = "slack-reminder";
      rev = "v0.1.1";
      fetchSubmodules = false;
      sha256 = "sha256-1MzRZ8E1wtwThnaXteMkAapX5kLFbEi3ix1csatSFF8=";
    };
  };
  sort-package-json = {
    pname = "sort-package-json";
    version = "v3.4.0";
    src = fetchFromGitHub {
      owner = "keithamus";
      repo = "sort-package-json";
      rev = "v3.4.0";
      fetchSubmodules = false;
      sha256 = "sha256-CnMWuokQistBfvyyPHJTqAlVj+8r4CcZ8VGYRKB1Mmo=";
    };
  };
  tsgo = {
    pname = "tsgo";
    version = "d508afb";
    src = fetchurl {
      url = "https://github.com/microsoft/typescript-go/archive/d508afb.zip";
      sha256 = "sha256-F18AKdpVQJvQpWAbAOhs/bwpFI+KMcJwrhVWbmlekB8=";
    };
  };
  vim-startuptime = {
    pname = "vim-startuptime";
    version = "v1.3.2";
    src = fetchFromGitHub {
      owner = "rhysd";
      repo = "vim-startuptime";
      rev = "v1.3.2";
      fetchSubmodules = false;
      sha256 = "sha256-d6AXTWTUawkBCXCvMs3C937qoRUZmy0qCFdSLcWh0BE=";
    };
  };
}
