name: Setup nix environments
description: Setup nix environments with my own config

inputs:
  github-token:
    description: GitHub token for action
    required: true
  nix-path:
    description: Path to nix store
    default: nixpkgs=https://github.com/NixOS/nixpkgs/archive/refs/heads/nixpkgs-unstable.tar.gz

runs:
  using: composite
  steps:
    - name: Install nix
      uses: cachix/install-nix-action@fc6e360bedc9ee72d75e701397f0bb30dce77568 # v31.5.2
      with:
        nix_path: ${{ inputs.nix-path }}
        extra_nix_config: |
          experimental-features = nix-command flakes pipe-operators
          access-tokens = github.com=${{ inputs.github-token }}
          allowUnfree = true
    - uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad # v16
      with:
        name: omochice
